build:
  environment:
    php:
      version: 7.0.6
  dependencies:
    before:
      - composer install
      - bin/console doctrine:database:create
      - bin/console doctrine:schema:update --force
  tests:
    override:
      -
        command: phpunit --coverage-clover=my-coverage-file tests
        coverage:
          file: my-coverage-file
          format: php-clover

checks:
  php: true

filter:
  excluded_paths:
    - "app/*"
    - "bin/*"
    - "tests/*"
    - "var/*"
    - "src/AppBundle/Fixture/*"
