build:
    environment:
        php:
            version: 7.0.5
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file tests
                coverage:
                    file: my-coverage-file
                    format: php-clover
