language: php

php:
    - '7.0'
    - '7.1'

install:
    - composer install
    - pip install git+https://github.com/codecov/codecov-python@master#egg=codecov

script:
    - phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)