parameters:
#    parameter_name: value

services:

    # Loggers
    rockparade.api_logger:
        class: Monolog\Logger
        arguments: ['api']
        calls:
            - [pushHandler, ['@rockparade.api_handler']]
    rockparade.api_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%kernel.logs_dir%/api.log']
        calls:
            - [setFormatter, ['@rockparade.log_formatter']]
    rockparade.log_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%%\n"
    rockparade.exception_logger:
        class: Monolog\Logger
        arguments: ['api']
        calls:
            - [pushHandler, ['@rockparade.exception_logger_handler']]
    rockparade.exception_logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%kernel.logs_dir%/exceptions.log']
        calls:
            - [setFormatter, ['@rockparade.log_formatter']]

    # Repositories
    rockparade.user_repository:
        class: AppBundle\Entity\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\User']
    rockparade.band_repository:
        class: AppBundle\Entity\Repository\BandRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Band']
    rockparade.band_member_repository:
        class: AppBundle\Entity\Repository\BandMemberRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\BandMember']
    rockparade.role_repository:
        class: AppBundle\Entity\Repository\RoleRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Role']
    rockparade.event_repository:
        class: AppBundle\Entity\Repository\EventRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Event']

    # Services
    rockparade.band:
        class: AppBundle\Service\BandService
        arguments: ['@rockparade.band_repository', '@rockparade.band_member_repository', '@rockparade.user_repository']
    rockparade.user:
        class: AppBundle\Service\UserService
        arguments: ['@rockparade.vkontakte', '@rockparade.user_repository']
    rockparade.response_factory:
        class: AppBundle\Service\HttpResponseFactory
        arguments: ['@jms_serializer']
    rockparade.vkontakte:
        class: AppBundle\Service\Vkontakte\VkontakteClient
        arguments: ['%vkontakte.version%', '%vkontakte.client_id%', '%vkontakte.client_secret%']
    rockparade.token_authenticator:
         class: AppBundle\Service\Security\TokenAuthenticator
         arguments: ['@rockparade.user_repository']

    # Event listeners
    rockparade.event_listener.exception:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['%kernel.environment%', '%admin_email%', '@rockparade.exception_logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    rockparade.event_listener.controller:
        class: AppBundle\EventListener\ControllerListener
        arguments: ['@security.token_storage', '@rockparade.api_logger', '%kernel.environment%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: beforeController }
